version: '2.4'
services:

  nginx-app:
    image: ryanwclark/nginx:latest
    container_name: nginx-app
    labels:
    labels:
      - traefik.enable=true
      - traefik.http.routers.nginx-app.rule=Host(`nginx.example.com`)
      - traefik.http.services.nginx-app.loadbalancer.server.port=80
    volumes:
      - ./data:/www/html
      - ./logs:/www/logs
    environment:
      - ZABBIX_HOSTNAME=nginx-app
      - CONTAINER_LOG_LEVEL=DEBUG
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true
